include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'
  - project: 'security/security-tools'
    ref: 'v1'
    file: 'gitlab-ci.yml'

stages:
  - build
  - code-analysis
  - autotests
  - package-export
  - build-demo-2019
  - build-demo-2020
  - build-demo-2021
  - build-demo-2022
  - build-demo-6000
  - build-demo-ios
  - build-demo-macos
  - deploy
  - linking
  - security scan

variables:
  PROJECT_PATH: $CI_PROJECT_DIR
  AUTOTESTS_BAT: "cicd/autotests.bat"
  PACKAGE_BAT: "cicd/package-export.bat"
  PACKAGE_NAME: xsolla-commerce-sdk.unitypackage
  BUILD_ROOT_PATH: "Builds"
  BUILD_SCRIPT_WIN: "cicd/build-demo-win.bat"
  BUILD_SCRIPT_IOS: "cicd/build-demo-ios.sh"
  BUILD_SCRIPT_MACOS: "cicd/build-demo-mac.sh"
  BUILD_TARGET_WINDOWS: "StandaloneWindows64"
  BUILD_TARGET_WEBGL: "WebGL"
  BUILD_TARGET_ANDROID: "Android"
  BUILD_TARGET_IOS: "iOS"
  BUILD_TARGET_MACOS: "StandaloneOSX"
  UNITY_2019_VERSION: "2019.4.27f1"
  UNITY_2020_VERSION: "2020.3.14f1"
  UNITY_2021_VERSION: "2021.1.13f1"
  UNITY_2022_VERSION: "2022.3.26f1"
  UNITY_6000_VERSION: "6000.0.9f1"
  GIT_CLEAN_FLAGS: -ffdx

# =================================================================================================================
# DOCS

build doc:
  stage: build
  only:
    - /^v.*/
  image: node:14-alpine3.15
  script:
  - apk update && apk add doxygen graphviz ttf-freefont zip git
  - doxygen Documentation/Autogen/Doxyfile >/dev/null
  - git clone https://$GITHUB_ACCESS_TOKEN@github.com/xsolla/sdk-reference-parser-unity-ue.git
  - mkdir -p sdk-reference-parser-unity-ue/src
  - mkdir -p sdk-reference-parser-unity-ue/dist
  - mv Documentation/Autogen/html/ sdk-reference-parser-unity-ue/src >/dev/null
  - cd sdk-reference-parser-unity-ue
  - npm install
  - npm start
  - mv -v dist/html/* dist >/dev/null
  - cd dist && zip -r $CI_PROJECT_DIR/build.zip * >/dev/null
  artifacts:
    paths:
    - build.zip
  tags:
    - devops

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - /^v.*/
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual
  tags:
    - sshclient

current doc:
  extends:      .current doc
  only:
    - /^v.*/
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/unity-store
  tags:
    - sshclient

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - /^v.*/
  tags:
    - sshclient
  dependencies: []

# =================================================================================================================
# CODE ANALYSIS

analyze-code:
  stage: code-analysis
  allow_failure: true
  script:
    - call cicd\code-analysis.bat
  artifacts:
    name: "SDK_analyze_code_logs_%CI_COMMIT_REF_NAME%"
    when: on_failure
    paths:
      - Logs
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# AUTOTESTS

run_autotests:
  stage: autotests
  script:
    - call %AUTOTESTS_BAT% %PROJECT_PATH% %UNITY_2019_VERSION%
  artifacts:
    name: "AUTOTESTS_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Logs/autotest_results.txt
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows
    
# =================================================================================================================
# PACKAGE EXPORT

export_package:
  stage: package-export
  script:
    - call %PACKAGE_BAT% %PROJECT_PATH% %UNITY_2019_VERSION% %PACKAGE_NAME% %BUILD_ROOT_PATH%
  artifacts:
    name: "PACKAGE_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Logs/export_results.txt
      - Logs/create_results.txt
      - Logs/import_results.txt
      - Logs/xsolla-commerce-sdk.unitypackage
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# UNITY 2019

build-windows-2019:
  stage: build-demo-2019
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2019_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WINDOWS%
  artifacts:
    name: "%UNITY_2019_VERSION%_%BUILD_TARGET_WINDOWS%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WINDOWS%-%UNITY_2019_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-webgl-2019:
  stage: build-demo-2019
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2019_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WEBGL%
  artifacts:
    name: "%UNITY_2019_VERSION%_%BUILD_TARGET_WEBGL%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WEBGL%-%UNITY_2019_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-android-2019:
  stage: build-demo-2019
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2019_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_ANDROID%
  artifacts:
    name: "%UNITY_2019_VERSION%_%BUILD_TARGET_ANDROID%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_ANDROID%-%UNITY_2019_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# UNITY 2020

build-windows-2020:
  stage: build-demo-2020
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2020_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WINDOWS%
  artifacts:
    name: "%UNITY_2020_VERSION%_%BUILD_TARGET_WINDOWS%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WINDOWS%-%UNITY_2020_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-webgl-2020:
  stage: build-demo-2020
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2020_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WEBGL%
  artifacts:
    name: "%UNITY_2020_VERSION%_%BUILD_TARGET_WEBGL%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WEBGL%-%UNITY_2020_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-android-2020:
  stage: build-demo-2020
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2020_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_ANDROID%
  artifacts:
    name: "%UNITY_2020_VERSION%_%BUILD_TARGET_ANDROID%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_ANDROID%-%UNITY_2020_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# UNITY 2021

build-windows-2021:
  stage: build-demo-2021
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2021_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WINDOWS%
  artifacts:
    name: "%UNITY_2021_VERSION%_%BUILD_TARGET_WINDOWS%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WINDOWS%-%UNITY_2021_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-webgl-2021:
  stage: build-demo-2021
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2021_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WEBGL%
  artifacts:
    name: "%UNITY_2021_VERSION%_%BUILD_TARGET_WEBGL%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WEBGL%-%UNITY_2021_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-android-2021:
  stage: build-demo-2021
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2021_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_ANDROID%
  artifacts:
    name: "%UNITY_2021_VERSION%_%BUILD_TARGET_ANDROID%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_ANDROID%-%UNITY_2021_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# UNITY 2022

build-windows-2022:
  stage: build-demo-2022
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2022_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WINDOWS%
  artifacts:
    name: "%UNITY_2022_VERSION%_%BUILD_TARGET_WINDOWS%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WINDOWS%-%UNITY_2022_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-webgl-2022:
  stage: build-demo-2022
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2022_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WEBGL%
  artifacts:
    name: "%UNITY_2022_VERSION%_%BUILD_TARGET_WEBGL%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WEBGL%-%UNITY_2022_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-android-2022:
  stage: build-demo-2022
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_2022_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_ANDROID%
  artifacts:
    name: "%UNITY_2022_VERSION%_%BUILD_TARGET_ANDROID%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_ANDROID%-%UNITY_2022_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# UNITY 6000

.build-windows-6000:
  stage: build-demo-6000
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_6000_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WINDOWS%
  artifacts:
    name: "%UNITY_6000_VERSION%_%BUILD_TARGET_WINDOWS%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WINDOWS%-%UNITY_6000_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

.build-webgl-6000:
  stage: build-demo-6000
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_6000_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WEBGL%
  artifacts:
    name: "%UNITY_6000_VERSION%_%BUILD_TARGET_WEBGL%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WEBGL%-%UNITY_6000_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

.build-android-6000:
  stage: build-demo-6000
  script:
    - call %BUILD_SCRIPT_WIN% %PROJECT_PATH% %UNITY_6000_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_ANDROID%
  artifacts:
    name: "%UNITY_6000_VERSION%_%BUILD_TARGET_ANDROID%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_ANDROID%-%UNITY_6000_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# IOS DEMO

.build-ios-demo:
  stage: build-demo-ios
  resource_group: ios_build_group
  before_script:
    - export IOS_SIGN_TEAM_ID=$IOS_SIGN_TEAM_ID
    - export IOS_PROVISION_ID=$IOS_PROVISION_ID
    - chmod 755 fastlane/scripts/diawi_callback_helper.sh
  artifacts:
    when: always
    paths:
      - "Builds/build.log"
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - mac

build-ios-2019:
  extends: .build-ios-demo
  script:
    - sh $BUILD_SCRIPT_IOS $PROJECT_PATH $UNITY_2019_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_IOS

build-ios-2020:
  extends: .build-ios-demo
  script:
    - sh $BUILD_SCRIPT_IOS $PROJECT_PATH $UNITY_2020_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_IOS

build-ios-2021:
  extends: .build-ios-demo
  script:
    - sh $BUILD_SCRIPT_IOS $PROJECT_PATH $UNITY_2021_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_IOS

build-ios-2022:
  extends: .build-ios-demo
  script:
    - sh $BUILD_SCRIPT_IOS $PROJECT_PATH $UNITY_2022_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_IOS

build-ios-6000:
  extends: .build-ios-demo
  script:
    - sh $BUILD_SCRIPT_IOS $PROJECT_PATH $UNITY_6000_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_IOS

# =================================================================================================================
# MACOS DEMO

.build-macos-demo:
  stage: build-demo-macos
  resource_group: mac_build_group
  artifacts:
    when: always
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - mac

build-macos-2019:
  extends: .build-macos-demo
  script:
    - sh $BUILD_SCRIPT_MACOS $PROJECT_PATH $UNITY_2019_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_MACOS
  artifacts:
    paths:
      - Builds/$BUILD_TARGET_MACOS-$UNITY_2019_VERSION/XsollaInGameStoreUnityAsset.app

build-macos-2020:
  extends: .build-macos-demo
  script:
    - sh $BUILD_SCRIPT_MACOS $PROJECT_PATH $UNITY_2020_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_MACOS
  artifacts:
    paths:
      - Builds/$BUILD_TARGET_MACOS-$UNITY_2020_VERSION/XsollaInGameStoreUnityAsset.app

build-macos-2021:
  extends: .build-macos-demo
  script:
    - sh $BUILD_SCRIPT_MACOS $PROJECT_PATH $UNITY_2021_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_MACOS
  artifacts:
    paths:
      - Builds/$BUILD_TARGET_MACOS-$UNITY_2021_VERSION/XsollaInGameStoreUnityAsset.app

build-macos-2022:
  extends: .build-macos-demo
  script:
    - sh $BUILD_SCRIPT_MACOS $PROJECT_PATH $UNITY_2022_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_MACOS
  artifacts:
    paths:
      - Builds/$BUILD_TARGET_MACOS-$UNITY_2022_VERSION/XsollaInGameStoreUnityAsset.app

build-macos-6000:
  extends: .build-macos-demo
  script:
    - sh $BUILD_SCRIPT_MACOS $PROJECT_PATH $UNITY_6000_VERSION $BUILD_ROOT_PATH $BUILD_TARGET_MACOS
  artifacts:
    paths:
      - Builds/$BUILD_TARGET_MACOS-$UNITY_6000_VERSION/XsollaInGameStoreUnityAsset.app


# =========================================================================================================================
# DEPLOY DEMO STAGE

deploy stage:
    stage: deploy
    extends: .deploy stage
    variables:
        ENV: stage
    only:
        - /^stage-.*/
    except:
        - branches
    dependencies:
        - build-webgl-2019
    script:
        - /usr/local/bin/helper deploy ./Builds/${BUILD_TARGET_WEBGL}-${UNITY_2019_VERSION}

current stage:
    stage: linking
    extends: .current stage
    variables:
        ENV: stage
    only:
        - /^stage-.*/
    except:
        - branches
    script:
        - /usr/local/bin/helper current

stop stage:
    stage: deploy
    extends: .stop stage
    only:
        - /^stage-.*/
    except:
        - branches
    script:
        - /usr/local/bin/helper stop

# =========================================================================================================================
# DEPLOY DEMO PROD

deploy prod:
    stage: deploy
    extends: .deploy prod
    variables:
        ENV: prod
    dependencies:
        - build-webgl-2019
    script:
        - /usr/local/bin/helper deploy ./Builds/${BUILD_TARGET_WEBGL}-${UNITY_2019_VERSION}

current prod:
    stage: linking
    extends: .current prod
    variables:
        ENV: prod
    script:
        - /usr/local/bin/helper current

stop prod:
    stage: deploy
    extends: .stop prod
    script:
        - /usr/local/bin/helper stop
