include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'

stages:
  - build
  - deploy
  - linking

build doc:
  stage: build
  image: alpine
  script:
  - apk update && apk add doxygen graphviz ttf-freefont
  - doxygen Documentation/Autogen/Doxyfile
  - mv Documentation/Autogen/html/ docs/
  artifacts:
    paths:
    - docs

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - deploy_stage
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual

current doc:
  extends:      .current doc
  only:
    - deploy_stage
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/unity-store

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - deploy_stage
  dependencies: []
