include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'

stages:
  - build
  - deploy
  - linking

variables:
  PROJECT_PATH: $CI_PROJECT_DIR
  AUTOTESTS_BAT: "cicd/autotests.bat"
  PACKAGE_BAT: "cicd/package-export.bat"
  PACKAGE_NAME: xsolla-commerce-sdk.unitypackage
  BUILD_ROOT_PATH: "Builds"
  BUILD_SCRIPT_WIN: "cicd/build-demo-win.bat"
  BUILD_SCRIPT_MAC: "cicd/build-demo-mac.sh"
  BUILD_TARGET_WINDOWS: "StandaloneWindows64"
  BUILD_TARGET_WEBGL: "WebGL"
  BUILD_TARGET_ANDROID: "Android"
  BUILD_TARGET_IOS: "iOS"
  UNITY_2019_VERSION: "2019.4.27f1"
  UNITY_2020_VERSION: "2020.3.14f1"
  UNITY_2021_VERSION: "2021.1.13f1"
  GIT_CLEAN_FLAGS: -ffdx

build doc:
  stage: build
  image: alpine
  script:
  - apk update && apk add doxygen graphviz ttf-freefont zip git nodejs npm
  - doxygen Documentation/Autogen/Doxyfile >/dev/null
  - git clone https://$GITHUB_ACCESS_TOKEN@github.com/xsolla/sdk-reference-parser-unity-ue.git
  - mkdir -p sdk-reference-parser-unity-ue/src
  - mkdir -p sdk-reference-parser-unity-ue/dist
  - mv Documentation/Autogen/html/ sdk-reference-parser-unity-ue/src
  - cd sdk-reference-parser-unity-ue
  - npm install
  - npm start
  - cd dist/html && zip -r $CI_PROJECT_DIR/build.zip * >/dev/null
  - ls $CI_PROJECT_DIR -a
  artifacts:
    paths:
    - build.zip
  tags:
    - devops

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - /^v.*/
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual
  after_script:
    - echo https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
  tags:
    - sshclient

current doc:
  extends:      .current doc
  only:
    - /^v.*/
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/unity-store
  tags:
    - sshclient

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - /^v.*/
  tags:
    - sshclient
  dependencies: []